version: '3'

services:
  nano-node:
    image: nanocurrency/nano:latest
    container_name: nano-node
    hostname: nano-node
    environment:
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "7075:7075/udp"
      - "7075:7075"
      - "::1:7076:7076"
      - "::1:7078:7078"
    volumes:
      - ./nano-node:/root

  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    command: watchtower nano-node
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
